name: local-irbsm
channels:
   - nvidia
   - pytorch
dependencies:
   - pip
   - python=3.9.19
   - pytorch=2.0.1
   - pytorch-cuda=11.7
   - torchvision=0.15.2
   - pip:
      - h5py==3.10.0
      - mesh-to-sdf==0.0.15
      - numpy==1.26.3
      - opencv-python==4.11.0.86
      - point-cloud-utils==0.30.4
      - pykdtree==1.3.12
      - python-pycg==0.9.1 -f https://pycg.huangjh.tech/packages/index.html
      - pyvista==0.44.1
      - scikit-image==0.22.0
      - tqdm==4.66.1
      - trimesh==4.0.7
      - wandb==0.16.1